services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: postgres
      POSTGRES_DB: medsuite
  app:
    image: medsuite-backend
    ports:
      - 13000:3333
